version: '2'
services:
    consumerapp-app:
        image: consumerapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://consumerapp-mysql:3306/consumerapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    consumerapp-mysql:
        extends:
            file: mysql.yml
            service: consumerapp-mysql
